Use private OS distribution ZIPs in preference to public ones [DI-95] [5.2.z]
`SNAPSHOT` OS distribution ZIPs (e.g. [those indexed
here](https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/5.4.0-SNAPSHOT))
will no longer be generated, which causes problems with the
`hazelcast-docker` PR builder (amongst others).

Instead, the distribution ZIPs will be uploaded to a private AWS S3
bucket, which requires authentication.

**This was a non-trivial change**:
- Updated the default distribution in the Docker images to be the latest
released version
   - This is guaranteed to be available (without any credentials)
- Allows the `Dockerfile` to be executed normally outside of a build
(e.g. for the security scan)
- "latest released" is looked up via Maven to ensure this doesn't need
any explicit maintenance in future
- Added unit tests to all modified shell scripts
- Moved `get_hz_dist_zip` into `os_build.functions` (and same for EE)
- Created additional `maven.functions` script to support resolution of
"latest released" for a given artifact
   - This has to be duplicated for OS & EE because of Docker limitations
- Added `xmllint` to all the runner images that build anything as
required for the Maven stuff
- Updated the `get_dist` OS script to generate a pre-signed S3 URL to
get it from S3 rather than a Maven repository
- Because this requires authentication, had to move this from inside the
image to outside to access the repository secrets
- Simplified the `Dockerfile` arguments - the URL resolution is now
being done outside of the `Dockerfile` more of the time, meaning not
always required
   - removed the redundant `HZ_VARIANT` parameter
    - removed `HZ_VERSION` from OS and reduced usage in EE

For testing, I've been doing what I can locally to assert the results
between `master` and my branch are the same:
- E.G. the `build-pr.yml` doesn't pass locally for me on EE, I presume
due to some `act` incompatibility - so a milestone for my PR is to get
the same failure in the same place
- I've build the images locally (outside of `act`, just a plain `docker
buildx build hazelcast-os`) and they build ok.
- Because of the reliance on repository secrets, it's not possible to
run many tests properly

Fixes: [DI-95](https://hazelcast.atlassian.net/browse/DI-95)

[DI-95]:
https://hazelcast.atlassian.net/browse/DI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(cherry picked from commit 831ea17f6ec3a2cb2db05bb6069ef73b741d0dfe)

diff --git a/.github/workflows/build-pr.yml b/.github/workflows/build-pr.yml
--- a/.github/workflows/build-pr.yml
+++ b/.github/workflows/build-pr.yml
@@ -11,25 +11,51 @@ env:
   docker_log_file_ee: docker-hazelcast-ee-test.log
 
 jobs:
-  build-pr-oss:
+  build-pr:
     runs-on: ubuntu-latest
-
+    name: Build with default JDK
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
+      - name: Forbid .github/release_type file
+        run: |
+          if [ -f ".github/release_type" ]; then
+            echo "Error: .github/release_type file is not allowed in the PRs. It's used only during release creation"
+            exit 1
+          fi
+
+      - name: Install xmllint
+        uses: ./.github/actions/install-xmllint
+
       - name: Set up Docker
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: 'us-east-1'
 
       - name: Test scripts
         run: |
-          ./.github/scripts/test_scripts.sh
+          .github/scripts/test_scripts.sh
 
       - name: Build OSS image
         run: |
-          docker buildx build --load --tag hazelcast-oss:test hazelcast-oss
+          DOCKER_PATH=hazelcast-oss
+          # Extract from Dockerfile to avoid duplicate hardcoding of the latest SNAPSHOT version
+          HZ_VERSION=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' ${DOCKER_PATH}/Dockerfile)
+
+          . .github/scripts/oss-build.functions.sh
+          docker buildx build --load \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "" ${HZ_VERSION} "") \
+          --tag hazelcast-oss:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against OSS image
         timeout-minutes: 2
@@ -38,7 +64,16 @@ jobs:
 
       - name: Build Test EE image
         run: |
-          docker buildx build --load --tag hazelcast-ee:test hazelcast-enterprise
+          DOCKER_PATH=hazelcast-enterprise
+          # Extract from Dockerfile to avoid duplicate hardcoding of the latest SNAPSHOT version
+          HZ_VERSION=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' ${DOCKER_PATH}/Dockerfile)
+
+          . .github/scripts/ee-build.functions.sh
+          docker buildx build --load \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "" ${HZ_VERSION} "") \
+          --tag hazelcast-ee:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against EE image
         timeout-minutes: 2
@@ -54,9 +89,91 @@ jobs:
 
       - name: Store docker logs as artifact
         if: ${{ always() }}
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: docker-logs
           path: |
             ${{ env.docker_log_file_oss }}
             ${{ env.docker_log_file_ee }}
+
+  jdks:
+    uses: ./.github/workflows/get-supported-jdks.yaml
+
+  build-pr-custom-jdk:
+    runs-on: ubuntu-latest
+    needs: jdks
+    name: Build with jdk-${{ matrix.jdk }}
+    strategy:
+      fail-fast: false
+      matrix:
+        jdk: ${{ fromJSON(needs.jdks.outputs.jdks) }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v3
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: 'us-east-1'
+
+      - name: Build OSS image
+        run: |
+          DOCKER_PATH=hazelcast-oss
+          # Extract from Dockerfile to avoid duplicate hardcoding of the latest SNAPSHOT version
+          HZ_VERSION=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' ${DOCKER_PATH}/Dockerfile)
+
+          . .github/scripts/oss-build.functions.sh
+          docker buildx build --load \
+          --build-arg JDK_VERSION=${{ matrix.jdk }} \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "" ${HZ_VERSION} "") \
+          --tag hazelcast-oss:test \
+          ${DOCKER_PATH}
+
+      - name: Run smoke test against OSS image
+        timeout-minutes: 2
+        run: |
+          .github/scripts/simple-smoke-test.sh hazelcast-oss:test ${{ env.test_container_name_oss }}
+
+      - name: Build Test EE image
+        run: |
+          DOCKER_PATH=hazelcast-enterprise
+          # Extract from Dockerfile to avoid duplicate hardcoding of the latest SNAPSHOT version
+          HZ_VERSION=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' ${DOCKER_PATH}/Dockerfile)
+
+          . .github/scripts/ee-build.functions.sh
+          docker buildx build --load \
+          --build-arg JDK_VERSION=${{ matrix.jdk }} \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "" ${HZ_VERSION} "") \
+          --tag hazelcast-ee:test \
+          ${DOCKER_PATH}
+
+      - name: Run smoke test against EE image
+        timeout-minutes: 2
+        run: |
+          export HZ_LICENSEKEY=${{ secrets.HZ_ENTERPRISE_LICENSE }}
+          .github/scripts/simple-smoke-test.sh hazelcast-ee:test ${{ env.test_container_name_ee }}
+
+      - name: Get docker logs
+        if: ${{ always() }}
+        run: |
+          docker logs ${{ env.test_container_name_oss }} > ${{ env.docker_log_file_oss }}
+          docker logs ${{ env.test_container_name_ee }} > ${{ env.docker_log_file_ee }}
+
+      - name: Store docker logs as artifact
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-logs-jdk${{ matrix.jdk }}
+          path: |
+            ${{ env.docker_log_file_oss }}
+            ${{ env.docker_log_file_ee }}
+
