Simplify RedHat smoke test [DI-455] (#936)
When publishing a RedHat image, we run a simple smoke test on the image:
- setup a Hazelcast cluster using our Helm chart
- pull new platform + MC images _from RedHat Registry_
- run some simple checks on the running cluster

Specifically, were overriding _some_ of the [default values in the
chart's
`values.yaml`](https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/values.yaml)
with our own - but as were doing this via multiple layers of
indirection, it's not immediately obvious.

I think we can make this simpler to read by removing these layers of
indirection and inlining it instead.

Note - this **does not make it more stable**.

Changes:
- `smoke-test` script inlined into calling GitHub action step
   - removes passing arguments by index
- `values.yaml` (template) + `sed` template population replaced with
simply passing the arguments when we call `helm install`
   - makes it more obvious were just overriding some _default_ settings
- use default chart cluster size
- we tell the cluster to have `3` elements and then we check it actually
had `3`
- `3` is a arbitrary and the default - we should just use the default
and look it up from the chart instead
   - we shouldn't hardcode the value... twice
- use chart MC version
- rather than looking up the latest MC version from the (private) source
repo, we should simply use whatever version the chart suggests... which
just so happens [to be the latest
anyway](https://github.com/hazelcast/charts/blob/0de66af1b8086d71d0420b07f98f8f9dac8e9342/stable/hazelcast-enterprise/values.yaml#L349).
- this means we can remove all the architecture to support querying the
version and simplify further:
      - https://github.com/hazelcast/hazelcast-docker/pull/880
      - https://github.com/hazelcast/hazelcast-docker/pull/935
- improve format of errors in `cluster-verification`

[Example
execution](https://github.com/hazelcast/hazelcast-docker/actions/runs/14629941297)
- note the job actually failed due to (what I think is) flakiness, but
shows the cluster was set up properly.

Post-merge items:
- [ ] backport (will be painful)

_Partially addresses_:
[DI-455](https://hazelcast.atlassian.net/browse/DI-455)

Co-Authored-By: Nishaat Rajabali <12186256+nishaatr@users.noreply.github.com>

diff --git a/.github/workflows/build-pr.yml b/.github/workflows/build-pr.yml
--- a/.github/workflows/build-pr.yml
+++ b/.github/workflows/build-pr.yml
@@ -11,40 +11,101 @@ env:
   docker_log_file_ee: docker-hazelcast-ee-test.log
 
 jobs:
-  build-pr:
+  prepare:
     runs-on: ubuntu-latest
-    name: Build with default JDK
+    name: Prepare environment
+    outputs:
+      HZ_VERSION_OSS: ${{ steps.get_oss_vars.outputs.HZ_VERSION_OSS }}
+      HZ_VERSION_EE: ${{ steps.get_ee_vars.outputs.HZ_VERSION_EE }}
+      HAZELCAST_EE_ZIP_URL: ${{ steps.get_ee_vars.outputs.HAZELCAST_EE_ZIP_URL }}
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Set up Docker
-        uses: docker/setup-buildx-action@v2
+      - name: Forbid .github/release_type file
+        run: |
+          if [ -f ".github/release_type" ]; then
+            echo "Error: .github/release_type file is not allowed in the PRs. It's used only during release creation"
+            exit 1
+          fi
 
       - name: Test scripts
         run: |
           .github/scripts/test_scripts.sh
 
+      - name: Setup OSS variables
+        id: get_oss_vars
+        run: |
+          HZ_VERSION_OSS=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' hazelcast-oss/Dockerfile)
+          echo "HZ_VERSION_OSS=$HZ_VERSION_OSS" >> $GITHUB_OUTPUT
+
+      - name: Setup EE variables
+        id: get_ee_vars
+        run: |
+          HZ_VERSION_EE=$(awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' hazelcast-enterprise/Dockerfile)
+          . .github/scripts/ee-build.functions.sh
+          echo "HZ_VERSION_EE=$HZ_VERSION_EE" >> $GITHUB_OUTPUT
+          echo "HAZELCAST_EE_ZIP_URL=$(get_hz_dist_zip "" ${HZ_VERSION_EE})" >> $GITHUB_OUTPUT
+
+  build-pr:
+    runs-on: ubuntu-latest
+    name: Build with default JDK
+    needs: [ prepare ]
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v3
+
       - name: Build OSS image
         run: |
-          docker buildx build --load --tag hazelcast-oss:test hazelcast-oss
+          set -eEuo pipefail ${RUNNER_DEBUG:+-x}
+          DOCKER_PATH=hazelcast-oss
+          HZ_VERSION="${{ needs.prepare.outputs.HZ_VERSION_OSS }}"
+          
+          # duplicated block as GH doesn't support passing sensitive data between jobs
+          . .github/scripts/oss-build.functions.sh
+          export HZ_SNAPSHOT_INTERNAL_PASSWORD=${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
+          export HZ_SNAPSHOT_INTERNAL_USERNAME=${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
+          HAZELCAST_OSS_ZIP_URL=$(get_hz_dist_zip "" "${HZ_VERSION}")
+          
+          echo "Downloading distribution from $HAZELCAST_OSS_ZIP_URL"
+          
+          curl --fail --silent --show-error --location "$HAZELCAST_OSS_ZIP_URL" --output $DOCKER_PATH/hazelcast-distribution.zip; 
+          
+          docker buildx build --load \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --tag hazelcast-oss:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against OSS image
         timeout-minutes: 2
-        run: |
-          .github/scripts/simple-smoke-test.sh hazelcast-oss:test ${{ env.test_container_name_oss }}
+        run: |          
+          . .github/scripts/docker.functions.sh
+          .github/scripts/simple-smoke-test.sh hazelcast-oss:test ${{ env.test_container_name_oss }} oss ${{ needs.prepare.outputs.HZ_VERSION_OSS }} "$(get_default_jdk hazelcast-oss)"
 
       - name: Build Test EE image
         run: |
-          docker buildx build --load --tag hazelcast-ee:test hazelcast-enterprise
+          DOCKER_PATH=hazelcast-enterprise
+          HZ_VERSION="${{ needs.prepare.outputs.HZ_VERSION_EE }}"
+          curl --fail --silent --show-error --location "${{ needs.prepare.outputs.HAZELCAST_EE_ZIP_URL }}" --output $DOCKER_PATH/hazelcast-enterprise-distribution.zip;
+          
+          docker buildx build --load \
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --tag hazelcast-ee:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against EE image
         timeout-minutes: 2
         run: |
+          . .github/scripts/docker.functions.sh
           export HZ_LICENSEKEY=${{ secrets.HZ_ENTERPRISE_LICENSE }}
-          .github/scripts/simple-smoke-test.sh hazelcast-ee:test ${{ env.test_container_name_ee }}
+          .github/scripts/simple-smoke-test.sh hazelcast-ee:test ${{ env.test_container_name_ee }} ee ${{ needs.prepare.outputs.HZ_VERSION_EE }} "$(get_default_jdk hazelcast-enterprise)"
 
       - name: Get docker logs
         if: ${{ always() }}
@@ -66,7 +127,7 @@ jobs:
 
   build-pr-custom-jdk:
     runs-on: ubuntu-latest
-    needs: jdks
+    needs: [ jdks, prepare ]
     name: Build with jdk-${{ matrix.jdk }}
     strategy:
       fail-fast: false
@@ -83,26 +144,45 @@ jobs:
 
       - name: Build OSS image
         run: |
+          DOCKER_PATH=hazelcast-oss
+          HZ_VERSION="${{ needs.prepare.outputs.HZ_VERSION_OSS }}"
+          
+          # duplicated block as GH doesn't support passing sensitive data between jobs
+          . .github/scripts/oss-build.functions.sh
+          export HZ_SNAPSHOT_INTERNAL_PASSWORD=${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
+          export HZ_SNAPSHOT_INTERNAL_USERNAME=${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
+          HAZELCAST_OSS_ZIP_URL=$(get_hz_dist_zip "" "${HZ_VERSION}")
+          
+          curl --fail --silent --show-error --location "$HAZELCAST_OSS_ZIP_URL" --output $DOCKER_PATH/hazelcast-distribution.zip;
+
           docker buildx build --load \
           --build-arg JDK_VERSION=${{ matrix.jdk }} \
-          --tag hazelcast-oss:test hazelcast-oss
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --tag hazelcast-oss:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against OSS image
         timeout-minutes: 2
         run: |
-          .github/scripts/simple-smoke-test.sh hazelcast-oss:test ${{ env.test_container_name_oss }}
+          .github/scripts/simple-smoke-test.sh hazelcast-oss:test ${{ env.test_container_name_oss }} oss ${{ needs.prepare.outputs.HZ_VERSION_OSS }} ${{ matrix.jdk }}
 
       - name: Build Test EE image
         run: |
+          DOCKER_PATH=hazelcast-enterprise
+          HZ_VERSION="${{ needs.prepare.outputs.HZ_VERSION_EE }}"
+          curl --fail --silent --show-error --location "${{ needs.prepare.outputs.HAZELCAST_EE_ZIP_URL }}" --output $DOCKER_PATH/hazelcast-enterprise-distribution.zip;
+
           docker buildx build --load \
           --build-arg JDK_VERSION=${{ matrix.jdk }} \
-          --tag hazelcast-ee:test hazelcast-enterprise
+          --build-arg HZ_VERSION=${HZ_VERSION} \
+          --tag hazelcast-ee:test \
+          ${DOCKER_PATH}
 
       - name: Run smoke test against EE image
         timeout-minutes: 2
         run: |
           export HZ_LICENSEKEY=${{ secrets.HZ_ENTERPRISE_LICENSE }}
-          .github/scripts/simple-smoke-test.sh hazelcast-ee:test ${{ env.test_container_name_ee }}
+          .github/scripts/simple-smoke-test.sh hazelcast-ee:test ${{ env.test_container_name_ee }} ee ${{ needs.prepare.outputs.HZ_VERSION_EE }} ${{ matrix.jdk }}
 
       - name: Get docker logs
         if: ${{ always() }}
