Use internal snapshot repository for OSS snapshot image [DI-210][5.2.z] (#791)
Backport of:
-
https://github.com/hazelcast/hazelcast-docker/commit/114d45dc8f0ae106c4142b1dfd454357f6045722
- https://github.com/hazelcast/hazelcast-docker/pull/747
- https://github.com/hazelcast/hazelcast-docker/pull/754
- https://github.com/hazelcast/hazelcast-docker/pull/756
- https://github.com/hazelcast/hazelcast-docker/pull/765
- https://github.com/hazelcast/hazelcast-docker/pull/768
- https://github.com/hazelcast/hazelcast-docker/pull/766
- https://github.com/hazelcast/hazelcast-docker/pull/772
- https://github.com/hazelcast/hazelcast-docker/pull/774
- https://github.com/hazelcast/hazelcast-docker/pull/776
- https://github.com/hazelcast/hazelcast-docker/pull/775

I suggest to review it commit-by-commit

`SNAPSHOT` OS distribution ZIPs (e.g. [those indexed

here](https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/5.4.0-SNAPSHOT))
will no longer be generated, which causes problems with the
`hazelcast-docker` PR builder (amongst others).

Instead, the distribution ZIPs will be uploaded to a private AWS S3
bucket, which requires authentication.

**This was a non-trivial change**:
- Updated the default distribution in the Docker images to be the latest
released version
   - This is guaranteed to be available (without any credentials)
- Allows the `Dockerfile` to be executed normally outside of a build
(e.g. for the security scan)
- "latest released" is looked up via Maven to ensure this doesn't need
any explicit maintenance in future
- Added unit tests to all modified shell scripts
- Moved `get_hz_dist_zip` into `os_build.functions` (and same for EE)
- Created additional `maven.functions` script to support resolution of
"latest released" for a given artifact
   - This has to be duplicated for OS & EE because of Docker limitations
- Added `xmllint` to all the runner images that build anything as
required for the Maven stuff
- Updated the `get_dist` OS script to generate a pre-signed S3 URL to
get it from S3 rather than a Maven repository
- Because this requires authentication, had to move this from inside the
image to outside to access the repository secrets
- Simplified the `Dockerfile` arguments - the URL resolution is now
being done outside of the `Dockerfile` more of the time, meaning not
always required
   - removed the redundant `HZ_VARIANT` parameter
    - removed `HZ_VERSION` from OS and reduced usage in EE

For testing, I've been doing what I can locally to assert the results
between `master` and my branch are the same:
- E.G. the `build-pr.yml` doesn't pass locally for me on EE, I presume
due to some `act` incompatibility - so a milestone for my PR is to get
the same failure in the same place
- I've build the images locally (outside of `act`, just a plain `docker
buildx build hazelcast-os`) and they build ok.
- Because of the reliance on repository secrets, it's not possible to
run many tests properly

Fixes: [DI-95](https://hazelcast.atlassian.net/browse/DI-95)
[DI-210](https://hazelcast.atlassian.net/browse/DI-210)

[DI-95]:

https://hazelcast.atlassian.net/browse/DI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ



[DI-95]:
https://hazelcast.atlassian.net/browse/DI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---------

Co-authored-by: Jack Green <jack.green@hazelcast.com>

diff --git a/.github/workflows/tag_image_push_rhel.yml b/.github/workflows/tag_image_push_rhel.yml
--- a/.github/workflows/tag_image_push_rhel.yml
+++ b/.github/workflows/tag_image_push_rhel.yml
@@ -16,15 +16,16 @@ on:
         description: 'Version of the docker image e.g. 5.1.1, 5.1.1-1, defaults to HZ_VERSION'
         required: false
 jobs:
+  jdks:
+    uses: ./.github/workflows/get-supported-jdks.yaml
+
   build:
     defaults:
       run:
         shell: bash
     env:
+      REQUIRED_HZ_MAJOR_VERSION: 5
       SCAN_REGISTRY: "quay.io"
-      SCAN_REGISTRY_USER: ${{ secrets.SCAN_REGISTRY_USER }}
-      SCAN_REGISTRY_PASSWORD: ${{ secrets.SCAN_REGISTRY_PASSWORD }}
-      RHEL_PROJECT_ID: ${{ secrets.RHEL_PROJECT_ID }}
       TIMEOUT_IN_MINS: 60
       HZ_ENTERPRISE_LICENSE: ${{ secrets.HZ_ENTERPRISE_LICENSE }}
       OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
@@ -33,9 +34,14 @@ jobs:
       RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
       HZ_VERSION: ${{ github.event.inputs.HZ_VERSION }}
       RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION }}
-      PROJECT_NAME: hztest-${{ github.run_id }}-${{ github.run_attempt }}
+      PROJECT_NAME: test-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.jdk }}
 
     runs-on: ubuntu-latest
+    needs: jdks
+    strategy:
+      fail-fast: false
+      matrix:
+        jdk: ${{ fromJSON(needs.jdks.outputs.jdks) }}
     steps:
       - name: Set HZ version as environment variable
         run: |
@@ -54,6 +60,22 @@ jobs:
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
           fi
           echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
+
+      - name: Check HZ major version
+        run: |
+          HZ_MAJOR_VERSION=$(echo "${HZ_VERSION:0:1}")
+          if [[ "$HZ_MAJOR_VERSION" != "$REQUIRED_HZ_MAJOR_VERSION" ]]; then
+            echo "Major version must be ${REQUIRED_HZ_MAJOR_VERSION} but detected: ${HZ_MAJOR_VERSION}"
+            exit 1
+          fi
+          echo "HZ_MAJOR_VERSION=${HZ_MAJOR_VERSION}" >> $GITHUB_ENV
+
+      - name: Set scan registry secrets
+        run: |
+          echo "SCAN_REGISTRY_USER=${{ secrets[format('SCAN_REGISTRY_USER_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+          echo "SCAN_REGISTRY_PASSWORD=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+          echo "RHEL_PROJECT_ID=${{ secrets[format('RHEL_PROJECT_ID_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+
       - name: Checkout to Management Center Openshift
         uses: actions/checkout@v3
         with:
@@ -64,7 +86,7 @@ jobs:
       - name: Set Management Center Version to be used in the tests
         working-directory: management-center-openshift
         run: |
-          FILTERED_TAGS=$(git tag --list "v${HZ_EE_MAJOR_VERSION}*" |  grep -E -v '.*(BETA|-).*' )
+          FILTERED_TAGS=$(git tag --list "v${HZ_MAJOR_VERSION}*" |  grep -E -v '.*(BETA|-).*' )
           LATEST_TAG=$(echo -en "${FILTERED_TAGS}" | sort | tail -n 1)
           echo $LATEST_TAG
           echo "HZ_MC_VERSION=${LATEST_TAG:1}" >> $GITHUB_ENV
@@ -78,33 +100,52 @@ jobs:
         run: |
           SCAN_REPOSITORY=${SCAN_REGISTRY}/redhat-isv-containers/${RHEL_PROJECT_ID}
           echo "SCAN_REPOSITORY=${SCAN_REPOSITORY}" >> $GITHUB_ENV
-          echo "RHEL_IMAGE=${SCAN_REPOSITORY}:${RELEASE_VERSION}" >> $GITHUB_ENV
+          echo "RHEL_IMAGE=${SCAN_REPOSITORY}:${RELEASE_VERSION}-jdk${{ matrix.jdk }}" >> $GITHUB_ENV
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3.0.0
+
+      - name:  Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          version: v0.5.1
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: 'us-east-1'
+
+      - name: Log in to Red Hat Scan Registry
+        run: |
+          docker login ${SCAN_REGISTRY} -u ${SCAN_REGISTRY_USER} -p ${SCAN_REGISTRY_PASSWORD}
 
       - name: Build the Hazelcast Enterprise image
         run: |
           . .github/scripts/get-tags-to-push.sh 
-          TAGS_TO_PUSH=$(get_tags_to_push $RELEASE_VERSION)
+          . .github/scripts/docker.functions.sh
+          . .github/scripts/ee-build.functions.sh
+
+          DOCKER_DIR=hazelcast-enterprise
+          IMAGE_NAME=${SCAN_REPOSITORY}
+          DEFAULT_JDK="$(get_default_jdk $DOCKER_DIR)"
+
+          TAGS_TO_PUSH=$(get_tags_to_push ${{ env.RELEASE_VERSION }} "" "${{ matrix.jdk }}" "$DEFAULT_JDK")
           echo "TAGS_TO_PUSH=$TAGS_TO_PUSH"
           TAGS_ARG=""
           for tag in ${TAGS_TO_PUSH[@]}
           do
-             TAGS_ARG="${TAGS_ARG} --tag ${SCAN_REPOSITORY}:${tag}"
+            TAGS_ARG="${TAGS_ARG} --tag ${IMAGE_NAME}:${tag}"
           done
-          echo "TAGS_TO_PUSH=${TAGS_TO_PUSH}" >> $GITHUB_ENV
-          
-          echo "TAGS_ARG=$TAGS_ARG"
-          docker build \
-                --build-arg HZ_VERSION=${HZ_VERSION} \
-                ${TAGS_ARG} hazelcast-enterprise
 
-      - name: Log in to Red Hat Scan Registry and Push the Image
-        run: |
-          docker login ${SCAN_REGISTRY} -u ${SCAN_REGISTRY_USER} -p ${SCAN_REGISTRY_PASSWORD}
-          for tag in ${TAGS_TO_PUSH[@]}
-          do
-            echo "Pushing ${SCAN_REPOSITORY}:${tag}"
-            docker push ${SCAN_REPOSITORY}:${tag}
-          done
+          PLATFORMS="linux/amd64"
+          docker buildx build --push \
+            --build-arg HZ_VERSION=${{ env.HZ_VERSION }} \
+            --build-arg JDK_VERSION=${{ matrix.jdk }} \
+            --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "${{ matrix.variant }}" "${{ env.HZ_VERSION }}") \
+            ${TAGS_ARG} \
+            --platform=${PLATFORMS} $DOCKER_DIR
 
       - name: Install preflight tool
         run: |
@@ -121,7 +162,7 @@ jobs:
 
       - name: Wait for Scan to Complete
         run: |
-          VERSION=${RELEASE_VERSION}
+          VERSION=${RELEASE_VERSION}-jdk${{ matrix.jdk }}
           source .github/scripts/publish-rhel.sh
 
           wait_for_container_scan "$RHEL_PROJECT_ID" "$VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
@@ -167,14 +208,14 @@ jobs:
       - name: Get OpenShift events
         if: ${{ always() }}
         run: |
-          kubectl get events -n ${PROJECT_NAME} > openshift-events.log
+          kubectl get events -n ${PROJECT_NAME} > openshift-events-jdk${{ matrix.jdk }}.log
 
       - name: Store OpenShift events as artifact
         if: ${{ always() }}
         uses: actions/upload-artifact@v3
         with:
-          name: openshift-events.log
-          path: openshift-events.log
+          name: openshift-events-jdk${{ matrix.jdk }}.log
+          path: openshift-events-jdk${{ matrix.jdk }}.log
 
       - name: Clean up After Test
         if: always()
@@ -183,9 +224,15 @@ jobs:
 
       - name: Publish the Hazelcast Enterprise image
         run: |
-          VERSION=${RELEASE_VERSION}
+          VERSION=${RELEASE_VERSION}-jdk${{ matrix.jdk }}
           source .github/scripts/publish-rhel.sh
 
           publish_the_image "$RHEL_PROJECT_ID" "$VERSION" "$RHEL_API_KEY"
           wait_for_container_publish "$RHEL_PROJECT_ID" "$VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
           sync_tags "$RHEL_PROJECT_ID" "$VERSION" "$RHEL_API_KEY"
+
+      - name: Slack notification
+        uses: ./.github/actions/slack-notification
+        if: failure()
+        with:
+          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
