[CN-203] Update RHEL release script for supporting Hazelcast EE v4* and v5* (#305)

diff --git a/.github/workflows/tag_image_push_rhel.yml b/.github/workflows/tag_image_push_rhel.yml
--- a/.github/workflows/tag_image_push_rhel.yml
+++ b/.github/workflows/tag_image_push_rhel.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - "!*"
     tags:
+      - "v4.*"
       - "v5.*"
 
 jobs:
@@ -19,8 +20,6 @@ jobs:
       OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
       OCP_LOGIN_PASSWORD: ${{ secrets.OCP_LOGIN_PASSWORD }}
       OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
-      HZ_EE_RHEL_REPO_PASSWORD: ${{ secrets.HZ_EE_RHEL_REPO_PASSWORD }}
-      HZ_EE_RHEL_REPOSITORY: ${{ secrets.HZ_EE_RHEL_REPOSITORY }}
       RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
 
     runs-on: ubuntu-latest
@@ -32,11 +31,27 @@ jobs:
           path: management-center-openshift
           fetch-depth: 0
 
+      - name: Set Hazelcast Enterprise RHEL repository and password
+        working-directory: management-center-openshift
+        run: |
+          MAJOR_VERSION=$(echo "${GITHUB_REF:11}" | cut -d'.' -f 1 )
+          if [[ "$MAJOR_VERSION" == "v4" ]]; then
+            echo "HZ_EE_RHEL_REPOSITORY=${{ secrets.HZ_4_EE_RHEL_REPOSITORY }}" >> $GITHUB_ENV
+            echo "HZ_EE_RHEL_REPO_PASSWORD=${{ secrets.HZ_4_EE_RHEL_REPO_PASSWORD }}" >> $GITHUB_ENV
+          elif [[ "$MAJOR_VERSION" == "v5" ]]; then
+            echo "HZ_EE_RHEL_REPOSITORY=${{ secrets.HZ_5_EE_RHEL_REPOSITORY }}" >> $GITHUB_ENV
+            echo "HZ_EE_RHEL_REPO_PASSWORD=${{ secrets.HZ_5_EE_RHEL_REPO_PASSWORD }}" >> $GITHUB_ENV
+          else
+            echo "Major version cannot be ${MAJOR_VERSION}."
+            exit 1
+          fi
+          echo "HZ_EE_MAJOR_VERSION=${MAJOR_VERSION}" >> $GITHUB_ENV
+
       - name: Set Management Center Version to be used in the tests
         working-directory: management-center-openshift
         run: |
-          FILTERED_TAGS=$(git tag --list "v*" |  grep -E -v '.*(BETA|-).*' )
-          LATEST_TAG=$((IFS=$'\n' && echo "${FILTERED_TAGS[*]}") | sort | tail -n 1)
+          FILTERED_TAGS=$(git tag --list "${HZ_EE_MAJOR_VERSION}*" |  grep -E -v '.*(BETA|-).*' )
+          LATEST_TAG=$(echo -en "${FILTERED_TAGS}" | sort | tail -n 1)
           echo $LATEST_TAG
           echo "HZ_MC_VERSION=${LATEST_TAG:11}" >> $GITHUB_ENV
 
