DEBUG

diff --git a/.github/workflows/tag_image_push_rhel.yml b/.github/workflows/tag_image_push_rhel.yml
--- a/.github/workflows/tag_image_push_rhel.yml
+++ b/.github/workflows/tag_image_push_rhel.yml
@@ -5,63 +5,36 @@ on:
     branches:
       - "!*"
     tags:
+      - "v4.*"
       - "v5.*"
-      - "v6.*"
-      - '!*DEVEL*'
   workflow_dispatch:
     inputs:
       HZ_VERSION:
-        description: 'Version of Hazelcast to build the image for, e.g. 5.1.1, 5.0.1'
+        description: 'Version of Hazelcast to build the image for, e.g. 5.1.1, 5.0.1, 4.2.3'
         required: true
       RELEASE_VERSION:
         description: 'Version of the docker image e.g. 5.1.1, 5.1.1-1, defaults to HZ_VERSION'
         required: false
-      IS_LTS_OVERRIDE:
-        description: 'Override is LTS release'
-        required: false
-        type: choice
-        default: ''
-        options:
-          - ''
-          - 'false'
-          - 'true'
-      DRY_RUN:
-        description: 'Skip pushing the images to remote registry'
-        default: 'false'
-        type: choice
-        options:
-          - 'false'
-          - 'true'
-  workflow_call:
-    inputs:
-      HZ_VERSION:
-        type: string
-        description: 'Version of Hazelcast to build the image for, e.g. 5.1.1, 5.0.1'
-        required: true
-      RELEASE_VERSION:
-        type: string
-        description: 'Version of the docker image e.g. 5.1.1, 5.1.1-1, defaults to HZ_VERSION'
-        required: false
-      IS_LTS_OVERRIDE:
-        description: 'Override is LTS release'
-        required: false
-        type: string
-        default: ''
-      DRY_RUN:
-        description: 'Skip pushing the images to remote registry'
-        default: 'false'
-        type: string
 jobs:
   jdks:
     uses: ./.github/workflows/get-supported-jdks.yaml
 
   build:
+    defaults:
+      run:
+        shell: bash
     env:
+      REQUIRED_HZ_MAJOR_VERSION: 5
       SCAN_REGISTRY: "quay.io"
-      TIMEOUT_IN_MINS: 240
+      TIMEOUT_IN_MINS: 60
+      HZ_ENTERPRISE_LICENSE: ${{ secrets.HZ_ENTERPRISE_LICENSE }}
+      OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
+      OCP_LOGIN_PASSWORD: ${{ secrets.OCP_LOGIN_PASSWORD }}
+      OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
       RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
-      HZ_VERSION: ${{ inputs.HZ_VERSION }}
-      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
+      HZ_VERSION: ${{ github.event.inputs.HZ_VERSION }}
+      RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION }}
+      PROJECT_NAME: test-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.jdk }}
 
     runs-on: ubuntu-latest
     needs: jdks
@@ -71,53 +44,57 @@ jobs:
         jdk: ${{ fromJSON(needs.jdks.outputs.jdks) }}
     steps:
       - name: Set HZ version as environment variable
-        if: env.HZ_VERSION == ''
         run: |
-          echo "HZ_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
+          if [ -z "${{ env.HZ_VERSION }}" ]; then
+             HZ_VERSION=${GITHUB_REF:11}
+          else
+             HZ_VERSION=${{ env.HZ_VERSION }}
+          fi
+          echo "HZ_VERSION=${HZ_VERSION}" >> $GITHUB_ENV
 
       - name: Set Release version as environment variable
-        if: env.RELEASE_VERSION == ''
         run: |
-          echo "RELEASE_VERSION=${{ env.HZ_VERSION }}" >> $GITHUB_ENV
+          if [ -z "${{ env.RELEASE_VERSION }}" ]; then
+             RELEASE_VERSION=${HZ_VERSION}
+          else
+             RELEASE_VERSION=${{ env.RELEASE_VERSION }}
+          fi
+          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
 
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3.6.0
-
-      - name:  Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          version: v0.5.1
-
-      - uses: madhead/semver-utils@latest
-        id: version
-        with:
-          version: ${{ env.HZ_VERSION }}
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: 'us-east-1'
-
-      - name: Get Secrets
-        uses: aws-actions/aws-secretsmanager-get-secrets@v2
-        with:
-          secret-ids: |
-            OCP_LOGIN_USERNAME,CN/OCP_USERNAME
-            OCP_LOGIN_PASSWORD,CN/OCP_PASSWORD
-            OCP_CLUSTER_URL,CN/OCP_CLUSTER_URL
+      - name: Check HZ major version
+        run: |
+          HZ_MAJOR_VERSION=$(echo "${HZ_VERSION:0:1}")
+          if [[ "$HZ_MAJOR_VERSION" != "$REQUIRED_HZ_MAJOR_VERSION" ]]; then
+            echo "Major version must be ${REQUIRED_HZ_MAJOR_VERSION} but detected: ${HZ_MAJOR_VERSION}"
+            exit 1
+          fi
+          echo "HZ_MAJOR_VERSION=${HZ_MAJOR_VERSION}" >> $GITHUB_ENV
 
       - name: Set scan registry secrets
         run: |
-          echo "SCAN_REGISTRY_USER=${{ secrets[format('SCAN_REGISTRY_USER_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV
-          echo "SCAN_REGISTRY_PASSWORD=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV
-          echo "RHEL_PROJECT_ID=${{ secrets[format('RHEL_PROJECT_ID_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV
+          echo "SCAN_REGISTRY_USER=${{ secrets[format('SCAN_REGISTRY_USER_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+          echo "SCAN_REGISTRY_PASSWORD=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+          echo "RHEL_PROJECT_ID=${{ secrets[format('RHEL_PROJECT_ID_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
+
+      - name: Checkout to Management Center Openshift
+        uses: actions/checkout@v3
+        with:
+          repository: hazelcast/management-center-openshift
+          path: management-center-openshift
+          fetch-depth: 0
+
+      - name: Set Management Center Version to be used in the tests
+        working-directory: management-center-openshift
+        run: |
+          FILTERED_TAGS=$(git tag --list "v${HZ_MAJOR_VERSION}*" |  grep -E -v '.*(BETA|-).*' )
+          LATEST_TAG=$(echo -en "${FILTERED_TAGS}" | sort | tail -n 1)
+          echo $LATEST_TAG
+          echo "HZ_MC_VERSION=${LATEST_TAG:1}" >> $GITHUB_ENV
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
       - name: Set RHEL image as environment variable
         run: |
@@ -125,24 +102,20 @@ jobs:
           echo "SCAN_REPOSITORY=${SCAN_REPOSITORY}" >> $GITHUB_ENV
           echo "RHEL_IMAGE=${SCAN_REPOSITORY}:${RELEASE_VERSION}-jdk${{ matrix.jdk }}" >> $GITHUB_ENV
 
-      - name: Log in to Red Hat Scan Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.SCAN_REGISTRY }}
-          username: ${{ env.SCAN_REGISTRY_USER }}
-          password: ${{ env.SCAN_REGISTRY_PASSWORD }}
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3.0.0
 
-      - name: Check if latest EE LTS release
-        id: is_latest_lts
-        uses: ./.github/actions/check-if-latest-lts-release
+      - name:  Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
         with:
-          release_version: ${{ env.RELEASE_VERSION }}
-          is_lts_override: ${{ inputs.IS_LTS_OVERRIDE }}
+          version: v0.5.1
+
+      - name: Log in to Red Hat Scan Registry
+        run: |
+          docker login ${SCAN_REGISTRY} -u ${SCAN_REGISTRY_USER} -p ${SCAN_REGISTRY_PASSWORD}
 
       - name: Delete unpublished images
-        if: inputs.DRY_RUN != 'true'
         run: |
-          echo "111111111111111111111111111111111111111111111111111111"
           VERSION=${RELEASE_VERSION}-jdk${{ matrix.jdk }}
           source .github/scripts/publish-rhel.sh
 
@@ -152,14 +125,12 @@ jobs:
         run: |
           . .github/scripts/get-tags-to-push.sh 
           . .github/scripts/docker.functions.sh
-          . .github/scripts/ee-build.functions.sh
 
           DOCKER_DIR=hazelcast-enterprise
           IMAGE_NAME=${SCAN_REPOSITORY}
           DEFAULT_JDK="$(get_default_jdk $DOCKER_DIR)"
 
-          IS_LATEST_LTS="${{ steps.is_latest_lts.outputs.is_latest_lts }}"
-          TAGS_TO_PUSH=$(get_tags_to_push "${{ env.RELEASE_VERSION }}" "" "${{ matrix.jdk }}" "$DEFAULT_JDK" "$IS_LATEST_LTS")
+          TAGS_TO_PUSH=$(get_tags_to_push ${{ env.RELEASE_VERSION }} "${{ matrix.suffix }}" "${{ matrix.jdk }}" "$DEFAULT_JDK")
           echo "TAGS_TO_PUSH=$TAGS_TO_PUSH"
           TAGS_ARG=""
           for tag in ${TAGS_TO_PUSH[@]}
@@ -167,22 +138,12 @@ jobs:
             TAGS_ARG="${TAGS_ARG} --tag ${IMAGE_NAME}:${tag}"
           done
 
-          output=
-
           PLATFORMS="linux/amd64"
-
-          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
-            echo "DRY RUN: Skipping push for platforms ${PLATFORMS} and tags: ${TAGS_TO_PUSH}"
-          else
-            output=--push
-          fi
-
-          docker buildx build ${output} \
+          docker buildx build --push \
             --build-arg HZ_VERSION=${{ env.HZ_VERSION }} \
             --build-arg JDK_VERSION=${{ matrix.jdk }} \
-            --build-arg HAZELCAST_ZIP_URL=$(get_hz_dist_zip "" "${{ env.HZ_VERSION }}") \
             ${TAGS_ARG} \
-            --platform=${PLATFORMS} "${DOCKER_DIR}"
+            --platform=${PLATFORMS} $DOCKER_DIR
 
       - name: Install `preflight` OpenShift tool from GitHub
         uses: redhat-actions/openshift-tools-installer@v1
@@ -192,16 +153,13 @@ jobs:
           skip_cache: true
 
       - name: Run preflight scan
-        if: inputs.DRY_RUN != 'true'
         run: |
-          echo "2222222222222222222222222222222222222222222222222222222222222"
-          preflight check container "${RHEL_IMAGE}" \
+          ./preflight-linux-amd64 check container ${RHEL_IMAGE} \
           --submit --pyxis-api-token=${RHEL_API_KEY} \
-          --certification-component-id=${RHEL_PROJECT_ID} \
+          --certification-project-id=${RHEL_PROJECT_ID} \
           --docker-config ~/.docker/config.json
 
       - name: Wait for Scan to Complete
-        if: inputs.DRY_RUN != 'true'
         run: |
           VERSION=${RELEASE_VERSION}-jdk${{ matrix.jdk }}
           source .github/scripts/publish-rhel.sh
@@ -209,7 +167,6 @@ jobs:
           wait_for_container_scan "$RHEL_PROJECT_ID" "$VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
 
       - name: Publish the Hazelcast Enterprise image
-        if: inputs.DRY_RUN != 'true'
         run: |
           VERSION=${RELEASE_VERSION}-jdk${{ matrix.jdk }}
           source .github/scripts/publish-rhel.sh
